### ISSUE TITLE
GenerateSdkSplitPropertiesCommandTest fails with bzlmod

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_android#180]
Success without bzlmod:
```
$ USE_BAZEL_VERSION=7.0.0rc2 bazel test --enable_bzlmod=false --incompatible_enable_android_toolchain_resolution=false -- //src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/...
...
INFO: Elapsed time: 14.425s, Critical Path: 7.79s
INFO: 31 processes: 7 internal, 12 linux-sandbox, 12 worker.
INFO: Build completed successfully, 31 total actions
//src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties:GenerateSdkSplitPropertiesCommandTest PASSED in 0.8s
    PASSED  com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withNoSdkArchiveOrModuleConfig_fails (0.2s)
    PASSED  com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_readsManifestWithDuplicateValues_usesFirstValuesAndSucceeds (0.1s)
    PASSED  com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withSdkMissingFromConfig_fails (0.0s)
    PASSED  com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withModuleConfig_succeeds (0.0s)
    PASSED  com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withSdkArchive_succeeds (0.0s)
Test cases: finished with 5 passing and 0 failing out of 5 test cases
```

Failure with:
```
$ USE_BAZEL_VERSION=7.0.0rc2 bazel test --enable_bzlmod=true --incompatible_enable_android_toolchain_resolution=false -- //src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/...
FAIL: //src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties:GenerateSdkSplitPropertiesCommandTest (see /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/execroot/_main/bazel-out/k8-fastbuild/testlogs/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/GenerateSdkSplitPropertiesCommandTest/test.log)
INFO: From Testing //src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties:GenerateSdkSplitPropertiesCommandTest:
==================== Test output for //src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties:GenerateSdkSplitPropertiesCommandTest:
JUnit4 Test Runner
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.google.testing.junit.runner.junit4.JUnit4Runner (file:/usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/external/rules_java~7.0.6~toolchains~remote_java_tools/java_tools/Runner_deploy.jar)
WARNING: Please consider reporting this to the maintainers of com.google.testing.junit.runner.junit4.JUnit4Runner
WARNING: System::setSecurityManager will be removed in a future release
.E.E.E.E.E
Time: 0.466
There were 5 failures:
1) generateProperties_withNoSdkArchiveOrModuleConfig_fails(com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest)
value of: getStatusCode()
expected: 1
but was : 2
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withNoSdkArchiveOrModuleConfig_fails(GenerateSdkSplitPropertiesCommandTest.java:161)
2) generateProperties_readsManifestWithDuplicateValues_usesFirstValuesAndSucceeds(com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest)
value of:
    getOutput()
expected to be empty
but was:
    Could not invoke public void com.google.devtools.build.android.sandboxedsdktoolbox.mixin.HostAppInfoMixin.setManifestXmlTreePath(java.nio.file.Path) with /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/sandbox/linux-sandbox/87/execroot/_main/bazel-out/k8-fastbuild/bin/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/GenerateSdkSplitPropertiesCommandTest.runfiles/rules_android/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/testdata/xmltree_dump_with_duplicate_values.txt (java.lang.IllegalArgumentException: Invalid manifest xml tree file.)
    Usage: sandboxed-sdk-toolbox generate-sdk-split-properties
           --manifest-xml-tree=<manifestXmlTreePath>
           --output-properties=<outputPropertiesPath>
           --runtime-enabled-sdk-config=<runtimeEnabledSdkConfigPath>
           [--sdk-archive=<sdkArchivePath>]
           [--sdk-modules-config=<sdkModuleConfigPath>]
    Generate the SdkSplitProperties file for a sandboxed SDK dependency of an app.
          --manifest-xml-tree=<manifestXmlTreePath>
             Path to the manifest xml tree file, as generated by AAPT2 dump command.
          --output-properties=<outputPropertiesPath>
    
          --runtime-enabled-sdk-config=<runtimeEnabledSdkConfigPath>
    
          --sdk-archive=<sdkArchivePath>
    
          --sdk-modules-config=<sdkModuleConfigPath>
    
    
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.runCommandAndReturnProperties(GenerateSdkSplitPropertiesCommandTest.java:209)
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_readsManifestWithDuplicateValues_usesFirstValuesAndSucceeds(GenerateSdkSplitPropertiesCommandTest.java:125)
3) generateProperties_withSdkMissingFromConfig_fails(com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest)
value of: getStatusCode()
expected: 1
but was : 2
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withSdkMissingFromConfig_fails(GenerateSdkSplitPropertiesCommandTest.java:186)
4) generateProperties_withModuleConfig_succeeds(com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest)
value of:
    getOutput()
expected to be empty
but was:
    Could not invoke public void com.google.devtools.build.android.sandboxedsdktoolbox.mixin.HostAppInfoMixin.setManifestXmlTreePath(java.nio.file.Path) with /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/sandbox/linux-sandbox/87/execroot/_main/bazel-out/k8-fastbuild/bin/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/GenerateSdkSplitPropertiesCommandTest.runfiles/rules_android/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/testdata/valid_xmltree_dump.txt (java.lang.IllegalArgumentException: Invalid manifest xml tree file.)
    Usage: sandboxed-sdk-toolbox generate-sdk-split-properties
           --manifest-xml-tree=<manifestXmlTreePath>
           --output-properties=<outputPropertiesPath>
           --runtime-enabled-sdk-config=<runtimeEnabledSdkConfigPath>
           [--sdk-archive=<sdkArchivePath>]
           [--sdk-modules-config=<sdkModuleConfigPath>]
    Generate the SdkSplitProperties file for a sandboxed SDK dependency of an app.
          --manifest-xml-tree=<manifestXmlTreePath>
             Path to the manifest xml tree file, as generated by AAPT2 dump command.
          --output-properties=<outputPropertiesPath>
    
          --runtime-enabled-sdk-config=<runtimeEnabledSdkConfigPath>
    
          --sdk-archive=<sdkArchivePath>
    
          --sdk-modules-config=<sdkModuleConfigPath>
    
    
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.runCommandAndReturnProperties(GenerateSdkSplitPropertiesCommandTest.java:209)
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withModuleConfig_succeeds(GenerateSdkSplitPropertiesCommandTest.java:98)
5) generateProperties_withSdkArchive_succeeds(com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest)
value of:
    getOutput()
expected to be empty
but was:
    Could not invoke public void com.google.devtools.build.android.sandboxedsdktoolbox.mixin.HostAppInfoMixin.setManifestXmlTreePath(java.nio.file.Path) with /usr/local/google/home/jcater/.cache/bazel/_bazel_jcater/ddb4e20e0e2e6bca92f5deeef02ce168/sandbox/linux-sandbox/87/execroot/_main/bazel-out/k8-fastbuild/bin/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/GenerateSdkSplitPropertiesCommandTest.runfiles/rules_android/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/sdksplitproperties/testdata/valid_xmltree_dump.txt (java.lang.IllegalArgumentException: Invalid manifest xml tree file.)
    Usage: sandboxed-sdk-toolbox generate-sdk-split-properties
           --manifest-xml-tree=<manifestXmlTreePath>
           --output-properties=<outputPropertiesPath>
           --runtime-enabled-sdk-config=<runtimeEnabledSdkConfigPath>
           [--sdk-archive=<sdkArchivePath>]
           [--sdk-modules-config=<sdkModuleConfigPath>]
    Generate the SdkSplitProperties file for a sandboxed SDK dependency of an app.
          --manifest-xml-tree=<manifestXmlTreePath>
             Path to the manifest xml tree file, as generated by AAPT2 dump command.
          --output-properties=<outputPropertiesPath>
    
          --runtime-enabled-sdk-config=<runtimeEnabledSdkConfigPath>
    
          --sdk-archive=<sdkArchivePath>
    
          --sdk-modules-config=<sdkModuleConfigPath>
    
    
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.runCommandAndReturnProperties(GenerateSdkSplitPropertiesCommandTest.java:209)
	at com.google.devtools.build.android.sandboxedsdktoolbox.sdksplitproperties.GenerateSdkSplitPropertiesCommandTest.generateProperties_withSdkArchive_succeeds(GenerateSdkSplitPropertiesCommandTest.java:71)

FAILURES!!!
Tests run: 5,  Failures: 5
```

**Comment by katre** [comment]
Looks like this test was recently added by @lucasvtenorio .

**Comment by katre** [comment]
More of #171.

**Comment by ahumesky** [comment]
The problem comes down to this:
https://github.com/bazelbuild/rules_android/blob/cb3da40723625d325ff127dea88de288b9d196d4/src/tools/javatests/com/google/devtools/build/android/sandboxedsdktoolbox/utils/TestData.java#L30

The test finds its data using that util constant. Without bzlmod, `$TEST_SRCDIR/rules_android` works, but with bzlmod that becomes `$TEST_SRCDIR/_main`. I don't know why that would change under bzlmod. Both the WORKSPACE and WORKSPACE.bzlmod files set `workspace(name = "rules_android")`. I'm not sure how the test can know which is the correct one to use... I guess I can hack it up a little to check both.

**Comment by katre** [comment]
I believe the answer is "use the Java runfiles library" (https://cs.opensource.google/bazel/bazel/+/master:tools/java/runfiles/Runfiles.java).
