### ISSUE TITLE
Build fails when `--incremental_dexing` is disabled

### ISSUE THREAD

**Issue by Bencodes** [bazelbuild/rules_android#213]
Building the basic app in the example directory fails when incremental dexing is disabled.

```
❯ bazel build //... --enable_bzlmod=false --incremental_dexing=false
ERROR: /Users/blee/Projects/rules_android/examples/basicapp/java/com/basicapp/BUILD:3:15: in android_binary_internal rule //java/com/basicapp:basic_app_RESOURCES_DO_NOT_USE:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_blee/8e4cee2d42f78883958223cc7ffc1cf5/external/rules_android/rules/android_binary_internal/impl.bzl", line 1024, column 35, in impl
                return processing_pipeline.run(ctx, java_package, _PROCESSING_PIPELINE)
        File "/private/var/tmp/_bazel_blee/8e4cee2d42f78883958223cc7ffc1cf5/external/rules_android/rules/processing_pipeline.bzl", line 79, column 23, in _run
                info = execute(ctx, **target_ctx)
        File "/private/var/tmp/_bazel_blee/8e4cee2d42f78883958223cc7ffc1cf5/external/rules_android/rules/android_binary_internal/impl.bzl", line 358, column 43, in _process_dex
                _dex.process_monolithic_dexing(
        File "/private/var/tmp/_bazel_blee/8e4cee2d42f78883958223cc7ffc1cf5/external/rules_android/rules/dex.bzl", line 219, column 65, in _process_monolithic_dexing
                progress_message = "Converting %s to dex format" % input.short_path,
Error: 'NoneType' value has no field or method 'short_path'
ERROR: /Users/blee/Projects/rules_android/examples/basicapp/java/com/basicapp/BUILD:3:15: Analysis of target '//java/com/basicapp:basic_app_RESOURCES_DO_NOT_USE' failed
```

**Comment by ahumesky** [comment]
Looks like this needs to be `binary_jar` instead of `proguarded_jar`:

https://github.com/bazelbuild/rules_android/blob/6cd2cbb345eff9c94462498501d83cf700357113/rules/android_binary_internal/impl.bzl#L367

`proguarded_jar` will definitely be None if proguard isn't used:
https://github.com/bazelbuild/rules_android/blob/6cd2cbb345eff9c94462498501d83cf700357113/rules/android_binary_internal/impl.bzl#L264
