### ISSUE TITLE
Bazel Does Not Support @Config For in Robolectric 4.9.2 

### ISSUE THREAD

**Issue by EdbertChan** [bazelbuild/rules_android#303]
### Description of the bug:

Bazel does not support @Config annotation

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Branch for robolectric:
https://github.com/EdbertChan/SimpleBazelAndroidApp/tree/demonstrate_robolectric_simple_error

Reproduction steps are in the README. Note that in the case of legacy mode, not all resources are available. 

### Which operating system are you running Bazel on?

MacOS Ventura Version 13.1

### What is the output of `bazel info release`?

release 6.0.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
https://github.com/EdbertChan/SimpleBazelAndroidApp.git
```

### Any other information, logs, or outputs that you want to share?

Instructions for branch:

First, run this in non-legacy/binary mode:

bazel test //module_1:greeter_activity_test 

Observe that this test fails

Time: 1.135
There was 1 failure:
1) testConfig(com.example.bazel.GreeterTest)
org.junit.ComparisonFailure: expected:<"com.[uber.demo.app.id]"> but was:<"com.[example.bazel]">
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.example.bazel.GreeterTest.testConfig(GreeterTest.java:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:580)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:287)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ahumesky** [comment]
This was potentially fixed in the Starlark version of android_local_test in https://github.com/bazelbuild/rules_android, if it's still an issue there let's reopen this
